/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface InstallPopover {
    'iconPath': string;
    'installEvent': any;
    'path': string;
  }
  interface PwaInstall {
    'forceshow': boolean;
    'iconpath': string;
    'manifestpath': string;
  }
}

declare global {


  interface HTMLInstallPopoverElement extends Components.InstallPopover, HTMLStencilElement {}
  var HTMLInstallPopoverElement: {
    prototype: HTMLInstallPopoverElement;
    new (): HTMLInstallPopoverElement;
  };

  interface HTMLPwaInstallElement extends Components.PwaInstall, HTMLStencilElement {}
  var HTMLPwaInstallElement: {
    prototype: HTMLPwaInstallElement;
    new (): HTMLPwaInstallElement;
  };
  interface HTMLElementTagNameMap {
    'install-popover': HTMLInstallPopoverElement;
    'pwa-install': HTMLPwaInstallElement;
  }
}

declare namespace LocalJSX {
  interface InstallPopover extends JSXBase.HTMLAttributes<HTMLInstallPopoverElement> {
    'iconPath'?: string;
    'installEvent'?: any;
    'path'?: string;
  }
  interface PwaInstall extends JSXBase.HTMLAttributes<HTMLPwaInstallElement> {
    'forceshow'?: boolean;
    'iconpath'?: string;
    'manifestpath'?: string;
  }

  interface IntrinsicElements {
    'install-popover': InstallPopover;
    'pwa-install': PwaInstall;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


